version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Docker123!
      - MYSQL_DATABASE=forumdb
    volumes:
      - D:/belajar/database/mysql/forum/mysql_data:/var/lib/mysql
