### Register Test
POST http://localhost:8080/memberships/sign-up
Content-Type: application/json

{
    "username": "newuser",
    "password": "newpassword",
    "email": "newuser@example.com"
}

### Login Test
POST http://localhost:8080/memberships/login
Content-Type: application/json

{
    "email": "newuser@example.com",
    "password": "newpassword"
}

