### Register Test
POST http://localhost:8080/memberships/sign-up
Content-Type: application/json

{
    "username": "newuser",
    "password": "newpassword",
    "email": "newuser@example.com"
}

### Login Test
POST http://localhost:8080/memberships/login
Content-Type: application/json

{
    "email": "newuser@example.com",
    "password": "newpassword"
}

### Create Post Test
POST http://localhost:8080/posts/create-post
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzU5OTAzMjMsImlkIjoxLCJ1c2VybmFtZSI6Im5ldXVzZXIifQ.Bh9vUsrm82NAF2ua3nm1FRCbZ5TqC_Sxsk1IXdR4kS4
Content-Type: application/json

{
  "postTitle": "New Post",
  "postContent": "This is a new post",
  "postHashtag": ["General","New"]
}
